[project]
name = "fitlace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dj-database-url>=3.1.2",
    "django>=6.0.4",
    "django-tailwind>=4.4.2",
    "psycopg[binary]>=3.3.3",
    "python-decouple>=3.8",
]

[dependency-groups]
dev = [
    "cookiecutter>=2.7.1",
    "django-browser-reload>=1.21.0",
    "honcho>=2.0.0",
]
